export const APPOINTMENT_DETAIL_REQUEST = "APPOINTMENT_DETAIL_REQUEST";
export const APPOINTMENT_DETAIL_SUCCESS = "APPOINTMENT_DETAIL_SUCCESS";
export const APPOINTMENT_DETAIL_FAIL = "APPOINTMENT_DETAIL_FAIL";

export const APPOINTMENT_LIST_REQUEST = "APPOINTMENT_LIST_REQUEST";
export const APPOINTMENT_LIST_SUCCESS = "APPOINTMENT_LIST_SUCCESS";
export const APPOINTMENT_LIST_FAIL = "APPOINTMENT_LIST_FAIL";

export const MALE_APPOINTMENT_LIST_REQUEST = "MALE_APPOINTMENT_LIST_REQUEST";
export const MALE_APPOINTMENT_LIST_SUCCESS = "MALE_APPOINTMENT_LIST_SUCCESS";
export const MALE_APPOINTMENT_LIST_FAIL = "MALE_APPOINTMENT_LIST_FAIL";

export const APPOINTMENT_EMPLOYEE_LIST_REQUEST =
  "APPOINTMENT_EMPLOYEE_LIST_REQUEST";
export const APPOINTMENT_EMPLOYEE_LIST_SUCCESS =
  "APPOINTMENT_EMPLOYEE_LIST_SUCCESS";
export const APPOINTMENT_EMPLOYEE_LIST_FAIL = "APPOINTMENT_EMPLOYEE_LIST_FAIL";

export const FEMALE_APPOINTMENT_LIST_REQUEST =
  "FEMALE_APPOINTMENT_LIST_REQUEST";
export const FEMALE_APPOINTMENT_LIST_SUCCESS =
  "FEMALE_APPOINTMENT_LIST_SUCCESS";
export const FEMALE_APPOINTMENT_LIST_FAIL = "FEMALE_APPOINTMENT_LIST_FAIL";

export const APPOINTMENT_NAMES_REQUEST = "APPOINTMENT_NAMES_REQUEST";
export const APPOINTMENT_NAMES_SUCCESS = "APPOINTMENT_NAMES_SUCCESS";
export const APPOINTMENT_NAMES_FAIL = "APPOINTMENT_NAMES_FAIL";

export const APPOINTMENT_CREATE_REQUEST = "APPOINTMENT_CREATE_REQUEST";
export const APPOINTMENT_CREATE_SUCCESS = "APPOINTMENT_CREATE_SUCCESS";
export const APPOINTMENT_CREATE_FAIL = "APPOINTMENT_CREATE_FAIL";

export const APPOINTMENT_BARBER_LIST_FAIL = "APPOINTMENT_BARBER_LIST_FAIL";
export const APPOINTMENT_BARBER_LIST_REQUEST =
  "APPOINTMENT_BARBER_LIST_REQUEST";
export const APPOINTMENT_BARBER_LIST_SUCCESS =
  "APPOINTMENT_BARBER_LIST_SUCCESS";

export const NEW_APPOINTMENT_FACILITY_INFO = "NEW_APPOINTMENT_FACILITY_INFO";
export const NEW_APPOINTMENT_BARBER_INFO = "NEW_APPOINTMENT_BARBER_INFO";
export const NEW_APPOINTMENT_SERVICES_INFO = "NEW_APPOINTMENT_SERVICES_INFO";
export const ADD_APPOINTMENT_SERVICES_INFO = "ADD_APPOINTMENT_SERVICES_INFO";
export const REMOVE_APPOINTMENT_SERVICES_INFO =
  "REMOVE_APPOINTMENT_SERVICES_INFO";
export const NEW_APPOINTMENT_DATE_INFO = "NEW_APPOINTMENT_DATE_INFO";
export const NEW_APPOINTMENT_TIME_INFO = "NEW_APPOINTMENT_TIME_INFO";
export const EMPTY_NEW_APPOINTMENT_FACILITY_INFO =
  "EMPTY_NEW_APPOINTMENT_FACILITY_INFO";
export const EMPTY_NEW_APPOINTMENT_BARBER_INFO =
  "EMPTY_NEW_APPOINTMENT_BARBER_INFO";
export const EMPTY_NEW_APPOINTMENT_SERVICES_INFO =
  "EMPTY_NEW_APPOINTMENT_SERVICES_INFO";
export const EMPTY_NEW_APPOINTMENT_DATE_INFO =
  "EMPTY_NEW_APPOINTMENT_DATE_INFO";
export const EMPTY_NEW_APPOINTMENT_TIME_INFO =
  "EMPTY_NEW_APPOINTMENT_TIME_INFO";
