export const FACILITY_DETAIL_REQUEST = "FACILITY_DETAIL_REQUEST";
export const FACILITY_DETAIL_SUCCESS = "FACILITY_DETAIL_SUCCESS";
export const FACILITY_DETAIL_FAIL = "FACILITY_DETAIL_FAIL";

export const FACILITY_LIST_REQUEST = "FACILITY_LIST_REQUEST";
export const FACILITY_LIST_SUCCESS = "FACILITY_LIST_SUCCESS";
export const FACILITY_LIST_FAIL = "FACILITY_LIST_FAIL";

export const MALE_FACILITY_LIST_REQUEST = "MALE_FACILITY_LIST_REQUEST";
export const MALE_FACILITY_LIST_SUCCESS = "MALE_FACILITY_LIST_SUCCESS";
export const MALE_FACILITY_LIST_FAIL = "MALE_FACILITY_LIST_FAIL";

export const FACILITY_EMPLOYEE_LIST_REQUEST = "FACILITY_EMPLOYEE_LIST_REQUEST";
export const FACILITY_EMPLOYEE_LIST_SUCCESS = "FACILITY_EMPLOYEE_LIST_SUCCESS";
export const FACILITY_EMPLOYEE_LIST_FAIL = "FACILITY_EMPLOYEE_LIST_FAIL";

export const FEMALE_FACILITY_LIST_REQUEST = "FEMALE_FACILITY_LIST_REQUEST";
export const FEMALE_FACILITY_LIST_SUCCESS = "FEMALE_FACILITY_LIST_SUCCESS";
export const FEMALE_FACILITY_LIST_FAIL = "FEMALE_FACILITY_LIST_FAIL";

export const FACILITY_NAMES_REQUEST = "FACILITY_NAMES_REQUEST";
export const FACILITY_NAMES_SUCCESS = "FACILITY_NAMES_SUCCESS";
export const FACILITY_NAMES_FAIL = "FACILITY_NAMES_FAIL";

export const FACILITY_CREATE_REQUEST = "FACILITY_CREATE_REQUEST";
export const FACILITY_CREATE_SUCCESS = "FACILITY_CREATE_SUCCESS";
export const FACILITY_CREATE_FAIL = "FACILITY_CREATE_FAIL";

export const FACILITY_BARBER_LIST_FAIL = "FACILITY_BARBER_LIST_FAIL";
export const FACILITY_BARBER_LIST_REQUEST = "FACILITY_BARBER_LIST_REQUEST";
export const FACILITY_BARBER_LIST_SUCCESS = "FACILITY_BARBER_LIST_SUCCESS";
