export const SERVICE_USER_REQUEST = "SERVICE_USER_REQUEST";
export const SERVICE_USER_SUCCESS = "SERVICE_USER_SUCCESS";
export const SERVICE_USER_FAIL = "SERVICE_USER_FAIL";

export const SERVICE_BARBER_REQUEST = "SERVICE_BARBER_REQUEST";
export const SERVICE_BARBER_SUCCESS = "SERVICE_BARBER_SUCCESS";
export const SERVICE_BARBER_FAIL = "SERVICE_BARBER_FAIL";

export const CREATE_SERVICE_REQUEST = "CREATE_SERVICE_REQUEST";
export const CREATE_SERVICE_SUCCESS = "CREATE_SERVICE_SUCCESS";
export const CREATE_SERVICE_FAIL = "CREATE_SERVICE_FAIL";

export const DELETE_SERVICE_REQUEST = "DELETE_SERVICE_REQUEST";
export const DELETE_SERVICE_SUCCESS = "DELETE_SERVICE_SUCCESS";
export const DELETE_SERVICE_FAIL = "DELETE_SERVICE_FAIL";

export const EDIT_SERVICE_INFO = "EDIT_SERVICE_INFO";
