export const SERVICE_USER_REQUEST = "SERVICE_USER_REQUEST";
export const SERVICE_USER_SUCCESS = "SERVICE_USER_SUCCESS";
export const SERVICE_USER_FAIL = "SERVICE_USER_FAIL";

export const SERVICE_NABARBER_REQUEST = "SERVICE_NABARBER_REQUEST";
export const SERVICE_NABARBER_SUCCESS = "SERVICE_NABARBER_SUCCESS";
export const SERVICE_NABARBER_FAIL = "SERVICE_NABARBER_FAIL";

export const SERVICE_BARBER_REQUEST = "SERVICE_BARBER_REQUEST";
export const SERVICE_BARBER_SUCCESS = "SERVICE_BARBER_SUCCESS";
export const SERVICE_BARBER_FAIL = "SERVICE_BARBER_FAIL";

export const CREATE_SERVICE_REQUEST = "CREATE_SERVICE_REQUEST";
export const CREATE_SERVICE_SUCCESS = "CREATE_SERVICE_SUCCESS";
export const CREATE_SERVICE_FAIL = "CREATE_SERVICE_FAIL";

export const EDIT_SERVICE_REQUEST = "EDIT_SERVICE_REQUEST";
export const EDIT_SERVICE_SUCCESS = "EDIT_SERVICE_SUCCESS";
export const EDIT_SERVICE_FAIL = "EDIT_SERVICE_FAIL";

export const DELETE_SERVICE_REQUEST = "DELETE_SERVICE_REQUEST";
export const DELETE_SERVICE_SUCCESS = "DELETE_SERVICE_SUCCESS";
export const DELETE_SERVICE_FAIL = "DELETE_SERVICE_FAIL";

export const SET_EDIT_SERVICE_INFO = "SET_EDIT_SERVICE_INFO";
export const EMPTY_EDIT_SERVICE_INFO = "EMPTY_EDIT_SERVICE_INFO";
