export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_DETAIL_REQUEST = "USER_DETAIL_REQUEST";
export const USER_DETAIL_SUCCESS = "USER_DETAIL_SUCCESS";
export const USER_DETAIL_FAIL = "USER_DETAIL_FAIL";

export const USER_LIST_REQUEST = "USER_LIST_REQUEST";
export const USER_LIST_SUCCESS = "USER_LIST_SUCCESS";
export const USER_LIST_FAIL = "USER_LIST_FAIL";

export const NORMAL_USER_LIST_REQUEST = "NORMAL_USER_LIST_REQUEST";
export const NORMAL_USER_LIST_SUCCESS = "NORMAL_USER_LIST_SUCCESS";
export const NORMAL_USER_LIST_FAIL = "NORMAL_USER_LIST_FAIL";

export const USER_NAMES_REQUEST = "USER_NAMES_REQUEST";
export const USER_NAMES_SUCCESS = "USER_NAMES_SUCCESS";
export const USER_NAMES_FAIL = "USER_NAMES_FAIL";

export const USER_CREATE_REQUEST = "USER_CREATE_REQUEST";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_CREATE_FAIL = "USER_CREATE_FAIL";

export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";

export const ADD_BARBER_FAIL = "ADD_BARBER_FAIL";
export const ADD_BARBER_REQUEST = "ADD_BARBER_REQUEST";
export const ADD_BARBER_SUCCESS = "ADD_BARBER_SUCCESS";
export const ADD_BARBER_RESET = "ADD_BARBER_RESET";

export const REMOVE_BARBER_FAIL = "REMOVE_BARBER_FAIL";
export const REMOVE_BARBER_REQUEST = "REMOVE_BARBER_REQUEST";
export const REMOVE_BARBER_SUCCESS = "REMOVE_BARBER_SUCCESS";
export const REMOVE_BARBER_RESET = "REMOVE_BARBER_RESET";
